{{- if .Values.layers.storage }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: openebs
            namespace: openebs
            path: storage/openebs
  template:
    metadata:
      name: "{{`{{name}}`}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/k8s-my-ass/infra-charts.git
        targetRevision: main
        path: "infra-charts/{{`{{path}}`}}"
        helm:
          valueFiles:
            - "values.common.yaml"
            - "values.test.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{namespace}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - Replace=true
          - ServerSideApply=true
          - PruneLast=true
{{- end }}
