argo-cd:
  global:
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
    logging:
      format: json

  configs:
    cm:
      exec.enabled: "true"
      statusbadge.enabled: "true"
      helm.secrets.enabled: "true"
      helm.valuesFileSchemas: >-
        secrets,secrets+age-import,secrets+age-import-kubernetes
      application.resourceTrackingMethod: label

  dex:
    enabled: false

  controller:
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 1000Mi

  redis:
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule

  server:
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
    ingress:
      enabled: false
      path: /argocd

  repoServer:
    image:
      repository: ghcr.io/k8s-my-ass/infra-images/argocd-repo-server
      tag: "3.4.3"

    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

  applicationSet:
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi

  notifications:
    tolerations:
      - key: node-role.kubernetes.io/infra
        effect: NoSchedule
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 128Mi
