openebs:
  loki:
    singleBinary:
      replicas: 1
      persistence:
        size: 1Gi
    minio:
      replicas: 1
      mode: standalone
      persistence:
        size: 2Gi
      rootUser: ENC[AES256_GCM,data:cLevaSDRU8zqPw==,iv:6PeZB7JxDwa/ey8ujk4vJHZrNqFesQADs40MzdQnePI=,tag:zQ5F7+BnyLMmomeN+5IWzg==,type:str]
      rootPassword: ENC[AES256_GCM,data:nYNsSYRpXt3fk+9T4Ao8Dg==,iv:ZhNzLNs1EaJ6lx/pxhv7FudWhg/JUNftV3eG1oSI4yA=,tag:BymQwFRJ4HWoZC4pZlatxQ==,type:str]
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      postJob:
        enabled: false
  alloy:
    logging_config:
      debugging: true
  engines:
    replicated:
      mayastor:
        enabled: false
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMS9PWlFrbW9pUFZJL3VX
        TDBrdTJoeVZHM1lQVmcxaHIwQktlYXI2RXdnCnU2UlcvK2ZPa0Y1dlpVUDNvaUg0
        UGprK2FNOTNYamo0N0lhNVJlYXg5ZTgKLS0tIFFLRndiN0ErQkl2Wk5YK1RKSXNM
        L1lMK3pZeVAxb1h0RWlyWGkzbVlBSFEK/L8GVu/QZUgf7I4hjYuTUNwG/J9gVZDN
        vtoZ9qs5tPlN0UMEDT4SXnDpa5VoUlb6/qekerkZweRp+qXRheehzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2ups0y2ktvt8ah75yh766awkz7j43ytfdc8cucsmpfcqagmq5lq8kt5uf
  encrypted_regex: ^(password|passwd|pwd|secret|token|apikey|accessKey|privateKey|rootUser|rootPassword)$
  lastmodified: "2026-06-14T18:05:09Z"
  mac: ENC[AES256_GCM,data:EesQKzKnrQDhLIbGEPdr4YPumDNRKyAIQx2VsqGE0tdQVuqfldPBSagfRCivco9j4aY8yfl5oVFODuxffsHOvoxgBLlgNDk3w39NcREaCKuU/m6HRanaiyQktLx6TbGiUo8D+9QfuShLfy3d1uRM/CjJdhgbpgOHuiq8mHYPj0E=,iv:OMAETTy38MBvOIqIDtLjNabmnedy5+D9iwSBjGrBvsY=,tag:Zv2tC80IdK1SWSnkccxQcw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
