openebs:
  loki:
    singleBinary:
      persistence:
        size: 10Gi

    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 2
        memory: 8Gi

  minio:
    replicas: 4
    persistence:
      size: 50Gi
