kube-prometheus-stack:
  grafana:
    adminPassword: ENC[AES256_GCM,data:koQRe5U=,iv:6irBuF+JJ9gVap0MZRC2BrqGg6d626srm/4Xc/sf+6M=,tag:QLCn62gVhM3vIfEKGWTc1g==,type:str]
    persistence:
      enabled: false
  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      retention: 1d
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoektCcnNOeHhRYXVFQzhJ
        Mzd1ZHNwQS9NTlFKc0Q4UjNIaFcrUWpYS1dNCmhGNExTbHY0QWVFamtlam1BNlc2
        ZW56b0FQVWd5dEIvN3o5akZpRUl6aVEKLS0tIEpJdis1VEV4aTBNNW9saU5TU2gy
        MUtrSC9pWFpHOWRleGNuU29jZkxvQjAKZH588iXJU3V75UxX8xSnTjB6AZljD94T
        t+ubi3anTc7pNbmn3gkDwJejjKBlfMBQN9SkmkKLTd2C7+7LOEhk+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1f2ups0y2ktvt8ah75yh766awkz7j43ytfdc8cucsmpfcqagmq5lq8kt5uf
  encrypted_regex: ^(password|passwd|pwd|secret|token|apikey|accessKey|privateKey|rootUser|rootPassword|adminUser|adminPassword)$
  lastmodified: "2026-06-15T19:18:04Z"
  mac: ENC[AES256_GCM,data:i6+phkXNfAhf/ulksioctoK+6bJmnOmo4SCw0tRo5V+kL6O5w1rhsgQmVoBvmmnO8mg9yR9lyY35Uvyv5UZuMZAPLbeHA4mocgsNOJUwfbGZHvK3JjPOQtz3gZu1KxhcCu2X8v+t6qPc+pAxM3h1czGMKyP6fEHw11E5yYJ2p2U=,iv:Icii5iH+lWvo4c1h4+RmU59Upkf7x1XE3D6xFR1D68o=,tag:IenhvlEpyO7XPpwUUsgCmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
