kube-prometheus-stack:
  grafana:
    adminPassword: ENC[AES256_GCM,data:FM+HPK+Rq6dB6ocZgUo3Xw==,iv:4JDbW73uxYmX3ahOhp4VL8KwF7sLr8viVDN0XNYlqBY=,tag:InqJzuYImxcecgtF2/peWA==,type:str]
    persistence:
      enabled: true
      storageClassName: openebs-hostpath
      size: 2Gi
  prometheus:
    prometheusSpec:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  alertmanager:
    alertmanagerSpec:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          memory: 128Mi
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMCtmbDFGOG1nSW93L2xQ
        RzNiUUNaN2FKQmpVU2VrTStkU1RqTVBJU0FVCk5vVldQY0RhT05aV0ppek9tWmtP
        WjhBVFpSRmo5aGpOM2V1bEhqSXE4TUEKLS0tIGpDdG94bkZZM1NTZ01xeGdIa3ZZ
        MW8zU3NSTmdvb1JVTzVvb2w5SnRFdUEK5/bCOBAHM2tdOHYv1jBxhbiUoM/8wT59
        zeb6liHWseX77nq+swU52+SuQ4lCtjfZw5d/1+RU0FnxLZMEOqFxYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fn9u8ayq5cdary9466n7dmd7g8kp0hgeuz7vs7yr7z7zeel2vs3sjlhgft
  encrypted_regex: ^(password|passwd|pwd|secret|token|apikey|accessKey|privateKey|rootUser|rootPassword|adminUser|adminPassword)$
  lastmodified: "2026-06-15T19:18:11Z"
  mac: ENC[AES256_GCM,data:1TkAneM2GNG/LmCFALxNrnBJDx5A7d2m9rym+g2467X0arzyJPZEHucNwgI1IhfMmYrlfrVEu+kGvzbZL3h/EirfKmkjG2uuQH0FAUC7UJfRIELH3WM/tLr1uE4tO/6qF1X7H6GkkIMl387Yn7WKJNX8HsAN7/6Zhw2pvNuEtlI=,iv:0VWcY+uNt3ZGur1mRYQ5cNaXPA3YXDrPlR95nz5yIxM=,tag:2FJvSonpu2nIAwTUdvImxA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
